Season 1
carlssonemil/orion pull request #13
Opened 2022-11-11 18:03 UTC by CrazyIsEasy

## Season 1 releases on November 16th

## Changelog

**- Added Season 1 Weapons**
- **Sniper Rifle:** Victus XMR (Launch)
- **Submachine Gun:** BAS-P (Launch)
- **Assault Rifle:** M13B (Launch)
- **Assault Rifle:** Chimera (Mid-Season)

**Note:** Since this game is based around camo challenges it's hard to update the tracker in advance without knowing the actual challenges for the camos. What's the best course of action for this? We can leave camos as placeholders until we know what the camo challenges are, but if users are already beginning to track, then it will reset when we update the camo name. Or we can wait until we get all the information to push an update, but on the downside, users have to wait to actually track their camos. Thoughts?

2022-11-12 11:33 UTC, carlssonemil commented
I think it's best to wait until we have all the details, or atleast the names of the camouflages. The challenge requirements we can add in continuously afterwards.

We could maybe add the weapon as "Coming soon", so that the users know that they are coming 🤔

2022-11-12 11:43 UTC, carlssonemil requested changes

2022-11-12 11:43 UTC, carlssonemil commented on src/data/defaults/progress/assaultRifles.js
> +	},
Leave empty for now.
```suggestion
	'M13B': {},

	'Chimera': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/defaults/progress/sniperRifles.js
> +	},
```suggestion
	'Victus XMR': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/defaults/progress/subMachineGuns.js
> +	},
```suggestion
	'BAS-P': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/requirements/weapons/assaultRifles.js
> +	},
```suggestion
	'M13B': {},

	'Chimera': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/requirements/weapons/sniperRifles.js
> +	},
```suggestion
	'Victus XMR': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/requirements/weapons/subMachineGuns.js
> +	},
```suggestion
	'BAS-P': {},
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/weapons/assaultRifles.js
> +const dlc = ['M13B', 'Chimera']
```suggestion
const dlc = ['M13B', 'Chimera']

const comingSoon['M13B', 'Chimera']
```

And then add a property below on the weapon object:

```javascript
comingSoon: comingSoon.includes(weapon)
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/weapons/sniperRifles.js
> +const dlc = ['Victus XMR']
```suggestion
const dlc = ['Victus XMR']

const comingSoon = ['Victus XMR']
```

2022-11-12 11:43 UTC, carlssonemil commented on src/data/weapons/subMachineGuns.js
> +const dlc = ['BAS-P']
```suggestion
const dlc = ['BAS-P']

const comingSoon = ['BAS-P']
```

2022-11-12 11:44 UTC, carlssonemil commented
I'll add a "Coming soon" label to the UI before this is merged 😃

2022-11-16 07:54 UTC, CrazyIsEasy commented
Added the camos and camo challenges for the Season 1 Launch Weapons!

2022-11-16 18:27 UTC, carlssonemil approved these changes
Looks good! You got a few merge conflicts it seems like 🤔 Try rebasing the main branch into your branch locally and try and fix the conflicts there!

2022-11-16 19:41 UTC, CrazyIsEasy commented
I think I did it, I hope I didn't break anything 😅

2022-11-16 21:08 UTC, carlssonemil approved these changes
Looks good to me! 🥳

2022-11-16 21:08 UTC, merged